# Copyright (c) 2025 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: deleting-confirmation-flag
  namespace: longhorn-system
value: "true"
